name: BADR

on:
  push:
    branches: [master, add-badr-pipeline]

jobs:
  celery-exporter:
    uses: TarteelAI/infra/.github/workflows/badr.yml@main
    with:
      image: tarteel/celery-exporter
      deployment: celery-exporter
      clusters: '["tarteel-v3"]'
    secrets: inherit
